# Generated by Django 3.1.6 on 2021-06-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210602_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='employees', to='employees.department'),
            preserve_default=False,
        ),
    ]
