# Generated by Django 3.1.6 on 2021-06-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='owner',
            new_name='department_chief',
        ),
    ]
